const blankDB = [
  {
    id: 4,
    nameGroup: "",
    price: 10000,
    gross: "",
    net: "",
    timeToCooking: 15,
    workshop: "",
    weight: "1000",
    image: "",
    name: "Заготовка в кг",
    descriptionOfTheTechnologicalProcess: "тест",
    longDescription: "",
    proteins: "10",
    fats: "10",
    carbohydrates: "10",
    calories: "170",
    comment: "",
    archive: false,
    idParent: 0,
    idChild: 0,
    idWarehouses: 0,
    blankInfo: [],
    ingredientInfo: [
      {
        weight: "1000",
        name: "ингредиент в кг",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 3,
          proteins: "5",
          idPoS: 0,
          fats: "4",
          carbohydrates: "7",
          calories: "84",
          weight: "0",
          name: "ингредиент в кг",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 1,
            name: "кг",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    unit: {
      id: 1,
      name: "кг",
    },
  },
  {
    id: 5,
    nameGroup: "",
    price: 1500,
    gross: "",
    net: "",
    timeToCooking: 100,
    workshop: "",
    weight: "1000",
    image: "",
    name: "Заготовка в литрах",
    descriptionOfTheTechnologicalProcess: "тест",
    longDescription: "",
    proteins: "10",
    fats: "10",
    carbohydrates: "10",
    calories: "170.0",
    comment: "",
    archive: false,
    idParent: 0,
    idChild: 0,
    idWarehouses: 0,
    blankInfo: [],
    ingredientInfo: [
      {
        weight: "1000",
        name: "ингредиент в литрах",
        unit: {
          id: 3,
          name: "л",
        },
        ingredient: {
          id: 4,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "0",
          name: "ингредиент в литрах",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 3,
            name: "л",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    unit: {
      id: 3,
      name: "л",
    },
  },
  {
    id: 6,
    nameGroup: "",
    price: 10000,
    gross: "",
    net: "",
    timeToCooking: 15,
    workshop: "",
    weight: "0",
    image: "",
    name: "Заготовка в шт",
    descriptionOfTheTechnologicalProcess: "тест",
    longDescription: "",
    proteins: "0",
    fats: "0",
    carbohydrates: "0",
    calories: "0",
    comment: "",
    archive: false,
    idParent: 0,
    idChild: 0,
    idWarehouses: 0,
    blankInfo: [],
    ingredientInfo: [
      {
        weight: "1",
        name: "ингредиент в в шт",
        unit: {
          id: 2,
          name: "шт",
        },
        ingredient: {
          id: 5,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "0",
          name: "ингредиент в в шт",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 2,
            name: "шт",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    unit: {
      id: 2,
      name: "шт",
    },
  },
  {
    id: 19,
    nameGroup: "",
    price: 0,
    gross: "",
    net: "",
    timeToCooking: 15,
    workshop: "",
    weight: "215",
    image: "",
    name: "Тестовая заготовка 13",
    descriptionOfTheTechnologicalProcess: "тест",
    longDescription: "",
    proteins: "12",
    fats: "10",
    carbohydrates: "16",
    calories: "194",
    comment: "",
    archive: false,
    idParent: 0,
    idChild: 0,
    idWarehouses: 0,
    blankInfo: [
      {
        idWarehouses: 0,
        weight: "25",
        name: "Заготовка в шт",
        sexshop: "",
        parentId: 19,
        unit: {
          id: 2,
          name: "шт",
        },
        blank: {
          id: 6,
          cli: 1,
          nameGroup: "",
          price: 10000,
          gross: "",
          net: "",
          timeToCooking: 15,
          workshop: "",
          weight: "0",
          image: "",
          name: "Заготовка в шт",
          descriptionOfTheTechnologicalProcess: "тест",
          longDescription: "",
          proteins: "0",
          fats: "0",
          carbohydrates: "0",
          calories: "0",
          comment: "",
          archive: false,
          idParent: 0,
          idChild: 0,
          idWarehouses: 0,
          ingredientInfo: [
            {
              weight: "1",
              name: "ингредиент в в шт",
              unit: {
                id: 2,
                name: "шт",
              },
              ingredient: {
                id: 5,
                proteins: "1",
                idPoS: 0,
                fats: "1",
                carbohydrates: "1",
                calories: "",
                weight: "0",
                name: "ингредиент в в шт",
                archive: false,
                idBlank: 0,
                idProduct: 0,
                idWarehouses: 0,
                unit: {
                  id: 2,
                  name: "шт",
                },
                cli: 1,
              },
              idWarehouses: 0,
              sexshop: "",
            },
          ],
          unit: {
            id: 2,
            name: "шт",
          },
        },
        addInfoBlanks: [],
      },
      {
        idWarehouses: 0,
        weight: "15",
        name: "Заготовка в кг",
        sexshop: "",
        parentId: 19,
        unit: {
          id: 1,
          name: "кг",
        },
        blank: {
          id: 4,
          cli: 1,
          nameGroup: "",
          price: 10000,
          gross: "",
          net: "",
          timeToCooking: 15,
          workshop: "",
          weight: "1000",
          image: "",
          name: "Заготовка в кг",
          descriptionOfTheTechnologicalProcess: "тест",
          longDescription: "",
          proteins: "10",
          fats: "10",
          carbohydrates: "10",
          calories: "170",
          comment: "",
          archive: false,
          idParent: 0,
          idChild: 0,
          idWarehouses: 0,
          ingredientInfo: [
            {
              weight: "1000",
              name: "ингредиент в кг",
              unit: {
                id: 1,
                name: "кг",
              },
              ingredient: {
                id: 3,
                proteins: "5",
                idPoS: 0,
                fats: "4",
                carbohydrates: "7",
                calories: "84",
                weight: "0",
                name: "ингредиент в кг",
                archive: false,
                idBlank: 0,
                idProduct: 0,
                idWarehouses: 0,
                unit: {
                  id: 1,
                  name: "кг",
                },
                cli: 1,
              },
              idWarehouses: 0,
              sexshop: "",
            },
          ],
          unit: {
            id: 1,
            name: "кг",
          },
        },
        addInfoBlanks: [],
      },
    ],
    ingredientInfo: [
      {
        weight: "200",
        name: "ингредиент в кг",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 3,
          proteins: "5",
          idPoS: 0,
          fats: "4",
          carbohydrates: "7",
          calories: "84",
          weight: "0",
          name: "ингредиент в кг",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 1,
            name: "кг",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "15",
        name: "ингредиент в в шт",
        unit: {
          id: 2,
          name: "шт",
        },
        ingredient: {
          id: 5,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "0",
          name: "ингредиент в в шт",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 2,
            name: "шт",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    unit: {
      id: 1,
      name: "кг",
    },
  },
];

export const getAllBlank = () => blankDB;
