const ingredientsDB = [
  {
    id: 2,
    proteins: "1",
    idPoS: 0,
    fats: "1",
    carbohydrates: "1",
    calories: "",
    weight: "1",
    name: "без игридиента",
    archive: false,
    idBlank: 0,
    idProduct: 0,
    idWarehouses: 0,
    unit: { id: 2, name: "шт" },
  },
  {
    id: 3,
    proteins: "0",
    idPoS: 0,
    fats: "0",
    carbohydrates: "20",
    calories: "",
    weight: "1",
    name: "рис",
    archive: false,
    idBlank: 0,
    idProduct: 0,
    idWarehouses: 0,
    unit: { id: 1, name: "кг" },
  },
  {
    id: 4,
    proteins: "1",
    idPoS: 0,
    fats: "1",
    carbohydrates: "1",
    calories: "",
    weight: "1",
    name: "водо",
    archive: false,
    idBlank: 0,
    idProduct: 0,
    idWarehouses: 0,
    unit: { id: 1, name: "кг" },
  },
  {
    id: 5,
    proteins: "2",
    idPoS: 0,
    fats: "3",
    carbohydrates: "5",
    calories: "",
    weight: "1",
    name: "рыба",
    archive: false,
    idBlank: 0,
    idProduct: 0,
    idWarehouses: 0,
    unit: {
      id: 1,
      name: "кг",
    },
  },
  {
    id: 6,
    proteins: "10",
    idPoS: 0,
    fats: "5",
    carbohydrates: "15",
    calories: "",
    weight: "0",
    name: "тесто",
    archive: false,
    idBlank: 0,
    idProduct: 0,
    idWarehouses: 0,
    unit: { id: 1, name: "кг" },
  },
  {
    id: 7,
    proteins: "0",
    idPoS: 0,
    fats: "50",
    carbohydrates: "0",
    calories: "",
    weight: "0",
    name: "жир",
    archive: false,
    idBlank: 0,
    idProduct: 0,
    idWarehouses: 0,
    unit: { id: 1, name: "кг" },
  },
];

export const getAllIngredients = () => ingredientsDB;
