const productsDB = [
  {
    id: 257,
    parentId: 31,
    nameGroup: "Тестовая категория 1",
    price: 10000,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 10,
    workshop: "",
    weight: "490",
    uuid: "f33febd8-ec2b-467e-8b0e-62ffeeef1323",
    idBrand: 0,
    image: "http://192.168.8.160:33000/data/default_files/default_image.png",
    descriptionOfTheTechnologicalProcess: "effe",
    productIsName: "Тесто для пиццыfef",
    longDescription: "",
    description: "",
    proteins: "5",
    fats: "4",
    carbohydrates: "6",
    calories: "86",
    comment: "",
    unit: {
      id: 1,
      name: "кг",
    },
    ingredientInfo: [
      {
        weight: "300",
        name: "ингредиент в кг",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 3,
          proteins: "5",
          idPoS: 0,
          fats: "4",
          carbohydrates: "7",
          calories: "84",
          weight: "0",
          name: "ингредиент в кг",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 1,
            name: "кг",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "100",
        name: "ингредиент в литрах",
        unit: {
          id: 3,
          name: "л",
        },
        ingredient: {
          id: 4,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "0",
          name: "ингредиент в литрах",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 3,
            name: "л",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [
      {
        idWarehouses: 0,
        weight: "10",
        name: "Заготовка в кг",
        sexshop: "",
        parentId: 0,
        unit: {
          id: 1,
          name: "кг",
        },
        blank: {
          id: 4,
          cli: 1,
          nameGroup: "",
          price: 10000,
          gross: "",
          net: "",
          timeToCooking: 15,
          workshop: "",
          weight: "1000",
          image: "",
          name: "Заготовка в кг",
          descriptionOfTheTechnologicalProcess: "тест",
          longDescription: "",
          proteins: "10",
          fats: "10",
          carbohydrates: "10",
          calories: "170",
          comment: "",
          archive: false,
          idParent: 0,
          idChild: 0,
          idWarehouses: 0,
          ingredientInfo: [
            {
              weight: "1000",
              name: "ингредиент в кг",
              unit: {
                id: 1,
                name: "кг",
              },
              ingredient: {
                id: 3,
                proteins: "5",
                idPoS: 0,
                fats: "4",
                carbohydrates: "7",
                calories: "84",
                weight: "0",
                name: "ингредиент в кг",
                archive: false,
                idBlank: 0,
                idProduct: 0,
                idWarehouses: 0,
                unit: {
                  id: 1,
                  name: "кг",
                },
                cli: 1,
              },
              idWarehouses: 0,
              sexshop: "",
            },
          ],
          unit: {
            id: 1,
            name: "кг",
          },
        },
        addInfoBlanks: [],
      },
      {
        idWarehouses: 0,
        weight: "80",
        name: "Заготовка в литрах",
        sexshop: "",
        parentId: 0,
        unit: {
          id: 3,
          name: "л",
        },
        blank: {
          id: 5,
          cli: 1,
          nameGroup: "",
          price: 1500,
          gross: "",
          net: "",
          timeToCooking: 100,
          workshop: "",
          weight: "1000",
          image: "",
          name: "Заготовка в литрах",
          descriptionOfTheTechnologicalProcess: "тест",
          longDescription: "",
          proteins: "10",
          fats: "10",
          carbohydrates: "10",
          calories: "170.0",
          comment: "",
          archive: false,
          idParent: 0,
          idChild: 0,
          idWarehouses: 0,
          ingredientInfo: [
            {
              weight: "1000",
              name: "ингредиент в литрах",
              unit: {
                id: 3,
                name: "л",
              },
              ingredient: {
                id: 4,
                proteins: "1",
                idPoS: 0,
                fats: "1",
                carbohydrates: "1",
                calories: "",
                weight: "0",
                name: "ингредиент в литрах",
                archive: false,
                idBlank: 0,
                idProduct: 0,
                idWarehouses: 0,
                unit: {
                  id: 3,
                  name: "л",
                },
                cli: 1,
              },
              idWarehouses: 0,
              sexshop: "",
            },
          ],
          unit: {
            id: 3,
            name: "л",
          },
        },
        addInfoBlanks: [],
      },
    ],
    modifications: [],
    menuInfo: [],
    archive: false,
  },
  {
    id: 258,
    parentId: 31,
    nameGroup: "Тестовая категория 1",
    price: 10000,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 15,
    workshop: "",
    weight: "50",
    uuid: "bcf1c027-ddad-4741-8939-437b774e8992",
    idBrand: 0,
    image: "http://192.168.8.160:33000/data/default_files/default_image.png",
    descriptionOfTheTechnologicalProcess: "тест",
    productIsName: "Тестeee",
    longDescription: "",
    description: "тест",
    proteins: "5",
    fats: "4",
    carbohydrates: "5",
    calories: "76",
    comment: "",
    unit: {
      id: 1,
      name: "кг",
    },
    ingredientInfo: [
      {
        weight: "10",
        name: "ингредиент в кг",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 3,
          proteins: "5",
          idPoS: 0,
          fats: "4",
          carbohydrates: "7",
          calories: "84",
          weight: "0",
          name: "ингредиент в кг",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 1,
            name: "кг",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "10",
        name: "ингредиент в в шт",
        unit: {
          id: 2,
          name: "шт",
        },
        ingredient: {
          id: 5,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "0",
          name: "ингредиент в в шт",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 2,
            name: "шт",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [
      {
        idWarehouses: 0,
        weight: "40",
        name: "Заготовка в кг",
        sexshop: "",
        parentId: 0,
        unit: {
          id: 1,
          name: "кг",
        },
        blank: {
          id: 4,
          cli: 1,
          nameGroup: "",
          price: 10000,
          gross: "",
          net: "",
          timeToCooking: 15,
          workshop: "",
          weight: "1000",
          image: "",
          name: "Заготовка в кг",
          descriptionOfTheTechnologicalProcess: "тест",
          longDescription: "",
          proteins: "10",
          fats: "10",
          carbohydrates: "10",
          calories: "170",
          comment: "",
          archive: false,
          idParent: 0,
          idChild: 0,
          idWarehouses: 0,
          ingredientInfo: [
            {
              weight: "1000",
              name: "ингредиент в кг",
              unit: {
                id: 1,
                name: "кг",
              },
              ingredient: {
                id: 3,
                proteins: "5",
                idPoS: 0,
                fats: "4",
                carbohydrates: "7",
                calories: "84",
                weight: "0",
                name: "ингредиент в кг",
                archive: false,
                idBlank: 0,
                idProduct: 0,
                idWarehouses: 0,
                unit: {
                  id: 1,
                  name: "кг",
                },
                cli: 1,
              },
              idWarehouses: 0,
              sexshop: "",
            },
          ],
          unit: {
            id: 1,
            name: "кг",
          },
        },
        addInfoBlanks: [],
      },
      {
        idWarehouses: 0,
        weight: "10",
        name: "Заготовка в шт",
        sexshop: "",
        parentId: 0,
        unit: {
          id: 2,
          name: "шт",
        },
        blank: {
          id: 6,
          cli: 1,
          nameGroup: "",
          price: 10000,
          gross: "",
          net: "",
          timeToCooking: 15,
          workshop: "",
          weight: "0",
          image: "",
          name: "Заготовка в шт",
          descriptionOfTheTechnologicalProcess: "тест",
          longDescription: "",
          proteins: "0",
          fats: "0",
          carbohydrates: "0",
          calories: "0",
          comment: "",
          archive: false,
          idParent: 0,
          idChild: 0,
          idWarehouses: 0,
          ingredientInfo: [
            {
              weight: "1",
              name: "ингредиент в в шт",
              unit: {
                id: 2,
                name: "шт",
              },
              ingredient: {
                id: 5,
                proteins: "1",
                idPoS: 0,
                fats: "1",
                carbohydrates: "1",
                calories: "",
                weight: "0",
                name: "ингредиент в в шт",
                archive: false,
                idBlank: 0,
                idProduct: 0,
                idWarehouses: 0,
                unit: {
                  id: 2,
                  name: "шт",
                },
                cli: 1,
              },
              idWarehouses: 0,
              sexshop: "",
            },
          ],
          unit: {
            id: 2,
            name: "шт",
          },
        },
        addInfoBlanks: [],
      },
    ],
    modifications: [],
    menuInfo: [],
    archive: false,
  },
  {
    id: 262,
    parentId: 31,
    nameGroup: "",
    price: 1200,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 11,
    workshop: "КУХНЯ",
    weight: "300",
    uuid: "0e983a39-61a4-442f-97d1-3794d49082bc",
    idBrand: 0,
    image: "http://192.168.8.160:33000/data/default_files/default_image.png",
    descriptionOfTheTechnologicalProcess: "выф",
    productIsName: "Лукавый 555",
    longDescription: "",
    description: "ывфа",
    proteins: "35",
    fats: "30",
    carbohydrates: "45",
    calories: "590",
    comment: "",
    unit: {
      id: 1,
      name: "кг",
    },
    ingredientInfo: [
      {
        weight: "100",
        name: "ингредиент в кг",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 3,
          proteins: "5",
          idPoS: 0,
          fats: "4",
          carbohydrates: "7",
          calories: "84",
          weight: "0",
          name: "ингредиент в кг",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 1,
            name: "кг",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [
      {
        idWarehouses: 0,
        weight: "100",
        name: "Заготовка в кг",
        sexshop: "",
        parentId: 0,
        unit: {
          id: 1,
          name: "кг",
        },
        blank: {
          id: 4,
          cli: 1,
          nameGroup: "",
          price: 10000,
          gross: "",
          net: "",
          timeToCooking: 15,
          workshop: "",
          weight: "1000",
          image: "",
          name: "Заготовка в кг",
          descriptionOfTheTechnologicalProcess: "тест",
          longDescription: "",
          proteins: "10",
          fats: "10",
          carbohydrates: "10",
          calories: "170",
          comment: "",
          archive: false,
          idParent: 0,
          idChild: 0,
          idWarehouses: 0,
          ingredientInfo: [
            {
              weight: "1000",
              name: "ингредиент в кг",
              unit: {
                id: 1,
                name: "кг",
              },
              ingredient: {
                id: 3,
                proteins: "5",
                idPoS: 0,
                fats: "4",
                carbohydrates: "7",
                calories: "84",
                weight: "0",
                name: "ингредиент в кг",
                archive: false,
                idBlank: 0,
                idProduct: 0,
                idWarehouses: 0,
                unit: {
                  id: 1,
                  name: "кг",
                },
                cli: 1,
              },
              idWarehouses: 0,
              sexshop: "",
            },
          ],
          unit: {
            id: 1,
            name: "кг",
          },
        },
        addInfoBlanks: [],
      },
      {
        idWarehouses: 0,
        weight: "100",
        name: "Тест",
        sexshop: "",
        parentId: 0,
        unit: {
          id: 1,
          name: "кг",
        },
        blank: {
          id: 18,
          cli: 1,
          nameGroup: "",
          price: 0,
          gross: "",
          net: "",
          timeToCooking: 15,
          workshop: "",
          weight: "400",
          image: "",
          name: "Тест",
          descriptionOfTheTechnologicalProcess: "аака",
          longDescription: "",
          proteins: "20",
          fats: "16",
          carbohydrates: "28",
          calories: "336",
          comment: "",
          archive: true,
          idParent: 0,
          idChild: 0,
          idWarehouses: 0,
          ingredientInfo: [
            {
              weight: "400",
              name: "ингредиент в кг",
              unit: {
                id: 1,
                name: "кг",
              },
              ingredient: {
                id: 3,
                proteins: "5",
                idPoS: 0,
                fats: "4",
                carbohydrates: "7",
                calories: "84",
                weight: "0",
                name: "ингредиент в кг",
                archive: false,
                idBlank: 0,
                idProduct: 0,
                idWarehouses: 0,
                unit: {
                  id: 1,
                  name: "кг",
                },
                cli: 1,
              },
              idWarehouses: 0,
              sexshop: "",
            },
          ],
          unit: {
            id: 1,
            name: "кг",
          },
        },
        addInfoBlanks: [],
      },
    ],
    modifications: [],
    menuInfo: [],
    archive: false,
  },
];

export const getAllProducts = () => productsDB;
