const productsDB = [
  {
    id: 23,
    parentId: 2,
    nameGroup: "Роллы",
    price: 50500,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 20,
    workshop: "Кухня",
    weight: "1750",
    uuid: "ca7526d4-f1b5-4688-b095-59e06aa2143b",
    idBrand: 0,
    image:
      "https://xn--b1ampelchila.xn--p1ai:33000/data/menucreatedish/1691068031727filename.png",
    descriptionOfTheTechnologicalProcess: "Без описания",
    productIsName: "И рыбку съесть",
    longDescription: "В состав блюда входи филадельфия и рыба",
    description: "",
    proteins: "1",
    fats: "1",
    carbohydrates: "7",
    calories: "40",
    comment: "",
    unit: { id: 1, name: "кг" },
    ingredientInfo: [
      {
        weight: "500.000",
        name: "рис",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 3,
          proteins: "0",
          idPoS: 0,
          fats: "0",
          carbohydrates: "20",
          calories: "",
          weight: "1",
          name: "рис",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "1000.000",
        name: "водо",
        unit: { id: 3, name: "л" },
        ingredient: {
          id: 4,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "1",
          name: "водо",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "250.000",
        name: "рыба",
        unit: { id: 1, name: "кг" },
        ingredient: {
          id: 5,
          proteins: "2",
          idPoS: 0,
          fats: "3",
          carbohydrates: "5",
          calories: "",
          weight: "1",
          name: "рыба",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 1,
            name: "кг",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [],
    modifications: [],
    menuInfo: [
      {
        id: 151,
        idPos: 5,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:34:52.355+00:00",
        archive: true,
      },
      {
        id: 156,
        idPos: 6,

        idBrand: 1,
        price: 50500,

        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.741+00:00",
        archive: true,
      },
      {
        id: 157,
        idPos: 7,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.781+00:00",
        archive: true,
      },
      {
        id: 158,
        idPos: 8,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.812+00:00",
        archive: true,
      },
      {
        id: 243,
        idPos: 2,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T19:22:18.236+00:00",
        archive: true,
      },
      {
        id: 342,
        idPos: 10,
        idBrand: 7,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-12T13:56:18.826+00:00",
        archive: true,
      },
    ],
    archive: false,
  },
  {
    id: 24,
    parentId: 2,
    nameGroup: "Роллы",
    price: 40500,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 20,
    workshop: "Кухня",
    weight: "220",
    uuid: "d247426b-dc63-4902-922f-22980f02e3b6",
    idBrand: 0,
    image:
      "https://xn--b1ampelchila.xn--p1ai:33000/data/menucreatedish/1691068115115filename.png",
    descriptionOfTheTechnologicalProcess: "Без описания",
    productIsName: "Тройничок,",
    longDescription: "",
    description: "",
    proteins: "1",
    fats: "1",
    carbohydrates: "1",
    calories: "17",
    comment: "",
    unit: { id: 1, name: "кг" },
    ingredientInfo: [
      {
        weight: "220",
        name: "без игридиента",
        unit: {
          id: 2,
          name: "шт",
        },
        ingredient: {
          id: 2,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "1",
          name: "без игридиента",
          archive: true,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 2, name: "шт" },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [],
    modifications: [],
    menuInfo: [
      {
        id: 226,
        idPos: 3,
        idBrand: 1,
        price: 40500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 24,
        dateCreate: "2023-08-09T14:46:11.377+00:00",
        archive: true,
      },
      {
        id: 227,
        idPos: 4,
        idBrand: 1,

        price: 40500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 24,
        dateCreate: "2023-08-09T14:46:12.060+00:00",
        archive: true,
      },
      {
        id: 228,
        idPos: 2,
        idBrand: 1,
        price: 40500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 24,
        dateCreate: "2023-08-09T14:46:17.541+00:00",
        archive: true,
      },
      {
        id: 229,
        idPos: 5,
        idBrand: 1,
        price: 40500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 24,
        dateCreate: "2023-08-09T14:46:18.170+00:00",
        archive: true,
      },
      {
        id: 230,
        idPos: 6,
        idBrand: 1,
        price: 40500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 24,
        dateCreate: "2023-08-09T14:46:18.563+00:00",
        archive: true,
      },
      {
        id: 231,
        idPos: 7,
        idBrand: 1,
        price: 40500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 24,
        dateCreate: "2023-08-09T14:46:18.919+00:00",
        archive: true,
      },
      {
        id: 232,
        idPos: 8,
        idBrand: 1,
        price: 40500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 24,
        dateCreate: "2023-08-09T14:46:19.303+00:00",
        archive: true,
      },
      {
        id: 346,
        idPos: 1,
        idBrand: 1,
        price: 40500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 24,
        dateCreate: "2023-08-12T13:56:22.269+00:00",
        archive: true,
      },
    ],
    archive: false,
  },
  {
    id: 25,
    parentId: 2,
    nameGroup: "Роллы",
    price: 41500,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 20,
    workshop: "Кухня",
    weight: "250",
    uuid: "dbf56782-f5b9-418e-9455-fdd377d79ea2",
    idBrand: 0,
    image:
      "https://xn--b1ampelchila.xn--p1ai:33000/data/menucreatedish/1691068183794filename.png",
    descriptionOfTheTechnologicalProcess: "Без описания",
    productIsName: "Жмот",
    longDescription: "",
    description: "",
    proteins: "1",
    fats: "1",
    carbohydrates: "1",
    calories: "17",
    comment: "",
    unit: {
      id: 1,
      name: "кг",
    },
    ingredientInfo: [
      {
        weight: "250",
        name: "без игридиента",
        unit: {
          id: 2,
          name: "шт",
        },
        ingredient: {
          id: 2,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "1",
          name: "без игридиента",
          archive: true,

          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 2,
            name: "шт",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [],
    modifications: [],
    menuInfo: [
      {
        id: 234,
        idPos: 6,
        idBrand: 1,
        price: 41500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 25,
        dateCreate: "2023-08-09T15:20:41.263+00:00",
        archive: true,
      },
      {
        id: 235,
        idPos: 8,
        idBrand: 1,
        price: 41500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 25,
        dateCreate: "2023-08-09T15:20:42.157+00:00",
        archive: true,
      },
      {
        id: 244,
        idPos: 2,
        idBrand: 1,
        price: 41500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 25,
        dateCreate: "2023-08-09T19:22:18.256+00:00",
        archive: true,
      },
      {
        id: 344,
        idPos: 10,
        idBrand: 7,
        price: 41500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 25,
        dateCreate: "2023-08-12T13:56:18.857+00:00",
        archive: true,
      },
      {
        id: 347,
        idPos: 1,
        idBrand: 1,
        price: 41500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 25,
        dateCreate: "2023-08-12T13:56:22.282+00:00",
        archive: true,
      },
    ],
    archive: false,
  },
  //---------------
  {
    id: 2351,
    parentId: 2,
    nameGroup: "Кебаб",
    price: 52500,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 20,
    workshop: "Кухня",
    weight: "1750",
    uuid: "ca7526d4-f1b5-4688-b095-59e06aa2143b",
    idBrand: 0,
    image:
      "https://xn--b1ampelchila.xn--p1ai:33000/data/menucreatedish/1691068031727filename.png",
    descriptionOfTheTechnologicalProcess: "Без описания",
    productIsName: "Кебабай",
    longDescription: "В состав блюда входи филадельфия и рыба",
    description: "",
    proteins: "1",
    fats: "1",
    carbohydrates: "7",
    calories: "40",
    comment: "",
    unit: { id: 1, name: "кг" },
    ingredientInfo: [
      {
        weight: "500.000",
        name: "рис",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 3,
          proteins: "0",
          idPoS: 0,
          fats: "0",
          carbohydrates: "20",
          calories: "",
          weight: "1",
          name: "рис",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "1000.000",
        name: "водо",
        unit: { id: 3, name: "л" },
        ingredient: {
          id: 4,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "1",
          name: "водо",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "250.000",
        name: "рыба",
        unit: { id: 1, name: "кг" },
        ingredient: {
          id: 5,
          proteins: "2",
          idPoS: 0,
          fats: "3",
          carbohydrates: "5",
          calories: "",
          weight: "1",
          name: "рыба",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 1,
            name: "кг",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [],
    modifications: [],
    menuInfo: [
      {
        id: 151,
        idPos: 5,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:34:52.355+00:00",
        archive: true,
      },
      {
        id: 156,
        idPos: 6,

        idBrand: 1,
        price: 50500,

        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.741+00:00",
        archive: true,
      },
      {
        id: 157,
        idPos: 7,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.781+00:00",
        archive: true,
      },
      {
        id: 158,
        idPos: 8,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.812+00:00",
        archive: true,
      },
      {
        id: 243,
        idPos: 2,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T19:22:18.236+00:00",
        archive: true,
      },
      {
        id: 342,
        idPos: 10,
        idBrand: 7,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-12T13:56:18.826+00:00",
        archive: true,
      },
    ],
    archive: false,
  },
  {
    id: 23451,
    parentId: 2,
    nameGroup: "Кебаб",
    price: 52500,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 20,
    workshop: "Кухня",
    weight: "1750",
    uuid: "ca7526d4-f1b5-4688-b095-59e06aa2143b",
    idBrand: 0,
    image:
      "https://xn--b1ampelchila.xn--p1ai:33000/data/menucreatedish/1691068031727filename.png",
    descriptionOfTheTechnologicalProcess: "Без описания",
    productIsName: "Печенька",
    longDescription: "",
    description: "",
    proteins: "1",
    fats: "1",
    carbohydrates: "7",
    calories: "40",
    comment: "",
    unit: { id: 1, name: "кг" },
    ingredientInfo: [
      {
        weight: "500.000",
        name: "рис",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 3,
          proteins: "0",
          idPoS: 0,
          fats: "0",
          carbohydrates: "20",
          calories: "",
          weight: "1",
          name: "рис",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "1000.000",
        name: "водо",
        unit: { id: 3, name: "л" },
        ingredient: {
          id: 4,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "1",
          name: "водо",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "250.000",
        name: "рыба",
        unit: { id: 1, name: "кг" },
        ingredient: {
          id: 5,
          proteins: "2",
          idPoS: 0,
          fats: "3",
          carbohydrates: "5",
          calories: "",
          weight: "1",
          name: "рыба",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 1,
            name: "кг",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [],
    modifications: [],
    menuInfo: [
      {
        id: 151,
        idPos: 5,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:34:52.355+00:00",
        archive: true,
      },
      {
        id: 156,
        idPos: 6,

        idBrand: 1,
        price: 50500,

        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.741+00:00",
        archive: true,
      },
      {
        id: 157,
        idPos: 7,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.781+00:00",
        archive: true,
      },
      {
        id: 158,
        idPos: 8,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.812+00:00",
        archive: true,
      },
      {
        id: 243,
        idPos: 2,
        idBrand: 1,
        price: 30500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T19:22:18.236+00:00",
        archive: true,
      },
      {
        id: 342,
        idPos: 10,
        idBrand: 7,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-12T13:56:18.826+00:00",
        archive: true,
      },
    ],
    archive: false,
  },
  {
    id: 23552431,
    parentId: 2,
    nameGroup: "Кебаб",
    price: 44650,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 20,
    workshop: "Кухня",
    weight: "1750",
    uuid: "ca7526d4-f1b5-4688-b095-59e06aa2143b",
    idBrand: 0,
    image:
      "https://xn--b1ampelchila.xn--p1ai:33000/data/menucreatedish/1691068031727filename.png",
    descriptionOfTheTechnologicalProcess: "Без описания",
    productIsName: "чай",
    longDescription: "В состав блюда входи филадельфия и рыба",
    description: "",
    proteins: "1",
    fats: "1",
    carbohydrates: "7",
    calories: "40",
    comment: "",
    unit: { id: 1, name: "кг" },
    ingredientInfo: [
      {
        weight: "500.000",
        name: "жир",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 3,
          proteins: "0",
          idPoS: 0,
          fats: "0",
          carbohydrates: "20",
          calories: "",
          weight: "1",
          name: "рис",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "1000.000",
        name: "водо",
        unit: { id: 3, name: "л" },
        ingredient: {
          id: 4,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "",
          weight: "1",
          name: "водо",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
      {
        weight: "250.000",
        name: "рыба",
        unit: { id: 1, name: "кг" },
        ingredient: {
          id: 5,
          proteins: "2",
          idPoS: 0,
          fats: "3",
          carbohydrates: "5",
          calories: "",
          weight: "1",
          name: "рыба",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: {
            id: 1,
            name: "кг",
          },
          cli: 1,
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [],
    modifications: [],
    menuInfo: [
      {
        id: 151,
        idPos: 5,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:34:52.355+00:00",
        archive: true,
      },
      {
        id: 156,
        idPos: 6,

        idBrand: 1,
        price: 50500,

        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.741+00:00",
        archive: true,
      },
      {
        id: 157,
        idPos: 7,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.781+00:00",
        archive: true,
      },
      {
        id: 158,
        idPos: 8,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T07:35:26.812+00:00",
        archive: true,
      },
      {
        id: 243,
        idPos: 2,
        idBrand: 1,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-09T19:22:18.236+00:00",
        archive: true,
      },
      {
        id: 342,
        idPos: 10,
        idBrand: 7,
        price: 50500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 23,
        dateCreate: "2023-08-12T13:56:18.826+00:00",
        archive: true,
      },
    ],
    archive: false,
  },
];

export const getAllProducts = () => productsDB;
