const productsDB = [
  {
    id: 124,
    parentId: 1,
    nameGroup: "",
    price: 10000,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 15,
    workshop: "",
    weight: "100",
    uuid: "ee60a8aa-ce25-44d5-afc8-22ff573cb208",
    idBrand: 0,
    image:
      "http://192.168.8.160:33000/data/menucreatedish/1691576662665filename.png",
    descriptionOfTheTechnologicalProcess: "ппп",
    productIsName: "Тест 1",
    longDescription: "",
    description: "ппп",
    proteins: "1",
    fats: "1",
    carbohydrates: "1",
    calories: "17",
    comment: "",
    unit: { id: 1, name: "кг" },
    ingredientInfo: [
      {
        weight: "100",
        name: "тест",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 1,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "21",
          weight: "0",
          name: "тест",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [],
    modifications: [],
    menuInfo: [
      {
        id: 38,
        idPos: 1,
        idBrand: 1,
        price: 10000,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T13:59:21.278+00:00",
        archive: true,
      },
      {
        id: 39,
        idPos: 2,
        idBrand: 1,
        price: 10000,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T13:59:21.298+00:00",
        archive: true,
      },
      {
        id: 51,
        idPos: 2,
        idBrand: 17,
        price: 99999900,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T14:07:09.426+00:00",
        archive: true,
      },
      {
        id: 54,
        idPos: 1,
        idBrand: 16,
        price: 9999900,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T14:07:28.692+00:00",
        archive: true,
      },
      {
        id: 56,
        idPos: 3,
        idBrand: 16,
        price: 99999900,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T14:07:29.868+00:00",
        archive: true,
      },
      {
        id: 57,
        idPos: 2,
        idBrand: 15,
        price: 999900,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T14:07:39.210+00:00",
        archive: true,
      },
      {
        id: 60,
        idPos: 1,
        idBrand: 2,
        price: 55500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T14:09:36.853+00:00",
        archive: true,
      },
      {
        id: 62,
        idPos: 3,
        idBrand: 2,
        price: 55500,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T14:09:39.102+00:00",
        archive: true,
      },
      {
        id: 64,
        idPos: 1,
        idBrand: 14,
        price: 10000,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T14:24:51.806+00:00",
        archive: true,
      },
      {
        id: 65,
        idPos: 2,
        idBrand: 14,
        price: 10000,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T14:24:51.828+00:00",
        archive: true,
      },
      {
        id: 66,
        idPos: 3,
        idBrand: 14,
        price: 10000,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 124,
        dateCreate: "2023-08-09T14:24:51.848+00:00",
        archive: true,
      },
    ],
    archive: false,
  },
  {
    id: 127,
    parentId: 1,
    nameGroup: "Роллы",
    price: 6,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 6,
    workshop: "",
    weight: "0",
    uuid: "0a45413f-a851-4685-9bda-7290c56cc1b5",
    idBrand: 0,
    image: "http://192.168.8.160:33000/data/default_files/default_image.png",
    descriptionOfTheTechnologicalProcess: "dd",
    productIsName: "dcdc",
    longDescription: "",
    description: "",
    proteins: "NaN",
    fats: "NaN",
    carbohydrates: "NaN",
    calories: "NaN",
    comment: "",
    unit: { id: 2, name: "шт" },
    ingredientInfo: [],
    blankInfo: [],
    modifications: [],
    menuInfo: [
      {
        id: 67,
        idPos: 2,
        idBrand: 1,
        price: 25000,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 127,
        dateCreate: "2023-08-09T15:13:36.220+00:00",
        archive: true,
      },
      {
        id: 68,
        idPos: 3,
        idBrand: 2,
        price: 5000,
        image: "",
        name: "",
        idCombo: 0,
        idGoods: 0,
        idProduct: 127,
        dateCreate: "2023-08-09T15:13:48.470+00:00",
        archive: true,
      },
    ],
    archive: false,
  },
  {
    id: 129,
    parentId: 1,
    nameGroup: "Роллы",
    price: 69000,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 5,
    workshop: "",
    weight: "1",
    uuid: "7e142421-6580-4a27-a788-670a246cf6e9",
    idBrand: 0,
    image: "http://192.168.8.160:33000/data/default_files/default_image.png",
    descriptionOfTheTechnologicalProcess: "dcd",
    productIsName: "Тест 1",

    longDescription: "",
    description: "",
    proteins: "0",
    fats: "0",

    carbohydrates: "0",
    calories: "20",
    comment: "",
    unit: {
      id: 1,
      name: "кг",
    },
    ingredientInfo: [
      {
        weight: "1",
        name: "тест",
        unit: {
          id: 1,
          name: "кг",
        },
        ingredient: {
          id: 1,
          proteins: "1",
          idPoS: 0,
          fats: "1",
          carbohydrates: "1",
          calories: "21",
          weight: "0",
          name: "тест",
          archive: false,
          idBlank: 0,
          idProduct: 0,
          idWarehouses: 0,
          unit: { id: 1, name: "кг" },
        },
        idWarehouses: 0,
        sexshop: "",
      },
    ],
    blankInfo: [],
    modifications: [],
    menuInfo: [],
    archive: false,
  },
  {
    id: 128,
    parentId: 7,
    nameGroup: "Тест",
    price: 5,
    sale: 0,
    priceWithSale: 0,
    timeToCooking: 10,
    workshop: "",
    weight: "0",
    uuid: "87258b7c-a4c9-4eb4-9474-4a1f843ae66a",
    idBrand: 0,
    image: "http://192.168.8.160:33000/data/default_files/default_image.png",
    descriptionOfTheTechnologicalProcess: "gbg",
    productIsName: "Тесто для пиццы",
    longDescription: "",
    description: "",
    proteins: "NaN",
    fats: "NaN",
    carbohydrates: "NaN",
    calories: "NaN",
    comment: "",
    unit: { id: 1, name: "кг" },
    ingredientInfo: [],
    blankInfo: [],
    modifications: [],
    menuInfo: [],
    archive: false,
  },
];

export const geAllProducts = () => productsDB;
